version: '3'

services:
  api: 
    build: ./chuck-norris-api
    command: npm start
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/chuck-norris-api
    
  react-app:
    build: ./react-ts-app
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/react-app